# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Madrid
    labels:
      - "dotnet"
      - "dependencies"
    reviewers:
      - asevillad
      - marcovgp
    assignees:
      - asevillad
      - marcovgp
    groups:
      net-breaking-changes:
        patterns:
          - "*"
        update-types:
          - "major"
      net-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Madrid
    labels:
      - "python"
      - "dependencies"
    reviewers:
      - asevillad
      - marcovgp
    assignees:
      - asevillad
      - marcovgp
    groups:
      python-breaking-changes:
        patterns:
          - "*"
        update-types:
          - "major"
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directories:
      - "/shared/src/iac"
      - "/workshop/src/iac"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Madrid
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - asevillad
      - marcovgp
    assignees:
      - asevillad
      - marcovgp
    groups:
      iac-breaking-changes:
        patterns:
          - "*"
        update-types:
          - "major"
      iac-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directories:
      - "/workshop/src/apps"
      - "/workshop/test/e2e"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Madrid
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - asevillad
      - marcovgp
    assignees:
      - asevillad
      - marcovgp
    groups:
      frontend-breaking-changes:
        patterns:
          - "*"
        update-types:
          - "major"
      frontend-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: "/"
    pull-request-branch-name:
      separator: "/"
    schedule:
      interval: monthly
      day: monday
      time: "08:00"
      timezone: Europe/Madrid
    labels:
      - "github-actions"
      - "dependencies"
    reviewers:
      - asevillad
      - marcovgp
    assignees:
      - asevillad
      - marcovgp
    groups:
      github-breaking-changes:
        patterns:
          - "*"
        update-types:
          - "major"
      github-actions-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
