version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo "Install started on `date`"
      - bash ./scripts/install_docker.sh
      - bash ./scripts/remove_cdk_profile.sh
      - npm install -g aws-cdk
      - npm install -g pnpm

  pre_build:
    commands:
      - pnpm install --frozen-lockfile
      - cd workshop/src/iac

  build:
    commands:
      - echo "Build started on `date`"
      - cdk deploy m47-workshop-2-0-net-paymentsapigateway-production-stack --require-approval never

  post_build:
    commands:
      - echo "Build completed on `date`"
