version: 0.2

# env:
#  parameter-store:
#    USER_POOL_ID: '/M47.workshop.Apps.Minimal.Api/Production/AWS/UserPoolId'

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      - echo "Install started on `date`"
      - bash ./scripts/remove_cdk_profile.sh
      - npm install -g aws-cdk
      - npm install -g envilder
      - npm install -g pnpm

  pre_build:
    commands:
      - pnpm install --frozen-lockfile
      # - export USER_POOL_ID=${USER_POOL_ID}
      - pnpx envilder --map=workshop/src/apps/user-shop/env-map.json --envfile=workshop/src/apps/user-shop/.env
      - pnpm --filter @workshop/user-shop build
      - cd workshop/src/iac

  build:
    commands:
      - echo "Build started on `date`"
      - cdk deploy m47-workshop-2-0-net-frontendusershop-production-stack --require-approval never

  post_build:
    commands:
      - echo "Build completed on `date`"
